### ISSUE TITLE
Error in console when generating End via Chunky

### ISSUE THREAD

**Issue by f1refa11** [justaureus/ReimagEND#15]
error:
```
[14:49:27 ERROR]: [com.dfsek.terra.addons.terrascript.script.StructureScript] Failed to generate structure at com.dfsek.terra.api.util.vector.Vector3Int@35eda26a
java.util.ConcurrentModificationException: null
        at java.util.HashMap.computeIfAbsent(HashMap.java:1221) ~[?:?]
        at com.dfsek.terra.addons.terrascript.script.functions.BlockFunction.getBlockState(BlockFunction.java:87) ~[?:?]
        at com.dfsek.terra.addons.terrascript.script.functions.BlockFunction.apply(BlockFunction.java:54) ~[?:?]
        at com.dfsek.terra.addons.terrascript.script.functions.BlockFunction.apply(BlockFunction.java:31) ~[?:?]
        at com.dfsek.terra.addons.terrascript.parser.lang.Block.apply(Block.java:27) ~[?:?]
        at com.dfsek.terra.addons.terrascript.parser.lang.keywords.looplike.IfKeyword.apply(IfKeyword.java:41) ~[?:?]
        at com.dfsek.terra.addons.terrascript.parser.lang.keywords.looplike.IfKeyword.apply(IfKeyword.java:23) ~[?:?]
        at com.dfsek.terra.addons.terrascript.parser.lang.Block.apply(Block.java:27) ~[?:?]
        at com.dfsek.terra.addons.terrascript.parser.lang.keywords.looplike.ForKeyword.apply(ForKeyword.java:39) ~[?:?]
        at com.dfsek.terra.addons.terrascript.parser.lang.keywords.looplike.ForKeyword.apply(ForKeyword.java:19) ~[?:?]
        at com.dfsek.terra.addons.terrascript.parser.lang.Block.apply(Block.java:27) ~[?:?]
        at com.dfsek.terra.addons.terrascript.parser.lang.keywords.looplike.ForKeyword.apply(ForKeyword.java:39) ~[?:?]
        at com.dfsek.terra.addons.terrascript.parser.lang.keywords.looplike.ForKeyword.apply(ForKeyword.java:19) ~[?:?]
        at com.dfsek.terra.addons.terrascript.parser.lang.Block.apply(Block.java:27) ~[?:?]
        at com.dfsek.terra.addons.terrascript.parser.lang.keywords.looplike.ForKeyword.apply(ForKeyword.java:39) ~[?:?]
        at com.dfsek.terra.addons.terrascript.parser.lang.keywords.looplike.ForKeyword.apply(ForKeyword.java:19) ~[?:?]
        at com.dfsek.terra.addons.terrascript.parser.lang.Block.apply(Block.java:27) ~[?:?]
        at com.dfsek.terra.addons.terrascript.parser.lang.Executable.execute(Executable.java:17) ~[?:?]
        at com.dfsek.terra.addons.terrascript.script.StructureScript.applyBlock(StructureScript.java:149) ~[?:?]
        at com.dfsek.terra.addons.terrascript.script.StructureScript.generate(StructureScript.java:135) ~[?:?]
        at com.dfsek.terra.addons.generation.feature.FeatureGenerationStage.lambda$populate$0(FeatureGenerationStage.java:73) ~[?:?]
        at com.dfsek.terra.api.structure.feature.BinaryColumn.forEach(BinaryColumn.java:89) ~[Terra-bukkit-6.3.1-BETA+73baaec6c-shaded.jar:?]
        at com.dfsek.terra.addons.generation.feature.FeatureGenerationStage.lambda$populate$1(FeatureGenerationStage.java:72) ~[?:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at com.dfsek.terra.addons.generation.feature.FeatureGenerationStage.lambda$populate$2(FeatureGenerationStage.java:67) ~[?:?]
        at com.dfsek.terra.addons.biome.pipeline.v2.BiomePipelineColumn.forRanges(BiomePipelineColumn.java:55) ~[?:?]
        at com.dfsek.terra.addons.generation.feature.FeatureGenerationStage.populate(FeatureGenerationStage.java:56) ~[?:?]
        at com.dfsek.terra.bukkit.generator.BukkitBlockPopulator.lambda$populate$0(BukkitBlockPopulator.java:31) ~[Terra-bukkit-6.3.1-BETA+73baaec6c-shaded.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at com.dfsek.terra.bukkit.generator.BukkitBlockPopulator.populate(BukkitBlockPopulator.java:31) ~[Terra-bukkit-6.3.1-BETA+73baaec6c-shaded.jar:?]
        at net.minecraft.world.level.chunk.ChunkGenerator.applyBiomeDecoration(ChunkGenerator.java:490) ~[paper-1.20.1.jar:git-Paper-196]
        at org.bukkit.craftbukkit.v1_20_R1.generator.CustomChunkGenerator.a(CustomChunkGenerator.java:301) ~[paper-1.20.1.jar:git-Paper-196]
        at com.dfsek.terra.bukkit.nms.v1_20_R1.NMSChunkGeneratorDelegate.a(NMSChunkGeneratorDelegate.java:76) ~[Terra-bukkit-6.3.1-BETA+73baaec6c-shaded.jar:?]
        at net.minecraft.world.level.chunk.ChunkStatus.lambda$static$11(ChunkStatus.java:127) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.world.level.chunk.ChunkStatus$SimpleGenerationTask.doWork(ChunkStatus.java:342) ~[?:?]
        at net.minecraft.world.level.chunk.ChunkStatus.generate(ChunkStatus.java:259) ~[paper-1.20.1.jar:git-Paper-196]
        at io.papermc.paper.chunk.system.scheduling.ChunkUpgradeGenericStatusTask.run(ChunkUpgradeGenericStatusTask.java:86) ~[paper-1.20.1.jar:git-Paper-196]
        at io.papermc.paper.chunk.system.scheduling.queue.RadiusAwarePrioritisedExecutor$Task.run(RadiusAwarePrioritisedExecutor.java:467) ~[paper-1.20.1.jar:git-Paper-196]
        at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadedTaskQueue$PrioritisedTask.executeInternal(PrioritisedThreadedTaskQueue.java:351) ~[paper-1.20.1.jar:git-Paper-196]
        at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadedTaskQueue.executeTask(PrioritisedThreadedTaskQueue.java:118) ~[paper-1.20.1.jar:git-Paper-196]
        at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadPool$PrioritisedThread.pollTasks(PrioritisedThreadPool.java:274) ~[paper-1.20.1.jar:git-Paper-196]
        at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedQueueExecutorThread.run(PrioritisedQueueExecutorThread.java:50) ~[paper-1.20.1.jar:git-Paper-196]
```

server: papermc 1.20.1
Terra version: 6.3.1
chunky version: 1.3.92
reimagend version: latest source from main

**Comment by f1refa11** [comment]
the error only appeared when i started generation using Chunky, after that no errors occurred.

**Comment by DeathShadez** [comment]
I believe this occurs when structures try to place blocks outside of the 3x3 chunk limit or outside the height limit max/min.
Should be fine to ignore.
