### ISSUE TITLE
Not possible to load pack

### ISSUE THREAD

**Issue by Skrayti** [justaureus/ReimagEND#19]
There's no possibility to use the pack
Console:
[20:44:20 INFO]: Preparing level "world"
[20:44:20 INFO]: [com.dfsek.terra.bukkit.nms.v1_20_R2.NMSInjectListener] Preparing to take over the world: world
[20:44:20 INFO]: [com.dfsek.terra.bukkit.nms.v1_20_R2.NMSInjectListener] Successfully injected into world.
[20:44:21 INFO]: [com.dfsek.terra.bukkit.nms.v1_20_R2.NMSInjectListener] Preparing to take over the world: world_nether
[20:44:21 INFO]: [com.dfsek.terra.bukkit.nms.v1_20_R2.NMSInjectListener] Successfully injected into world.
[20:44:21 ERROR]: [Terra] Could not set generator for default world 'world_the_end': Plugin 'Terra v6.4.1-BETA+3aef97738
java.lang.IllegalArgumentException: No such config pack "REIMAGEND"
        at com.dfsek.terra.bukkit.TerraBukkitPlugin.lambda$getDefaultWorldGenerator$1(TerraBukkitPlugin.java:185) ~[Terra-bukkit-6.4.1-BETA+3aef97738-shaded.jar:?]
        at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
        at com.dfsek.terra.bukkit.TerraBukkitPlugin.lambda$getDefaultWorldGenerator$2(TerraBukkitPlugin.java:184) ~[Terra-bukkit-6.4.1-BETA+3aef97738-shaded.jar:?]
        at java.util.HashMap.computeIfAbsent(HashMap.java:1220) ~[?:?]
        at com.dfsek.terra.bukkit.TerraBukkitPlugin.getDefaultWorldGenerator(TerraBukkitPlugin.java:183) ~[Terra-bukkit-6.4.1-BETA+3aef97738-shaded.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.getGenerator(CraftServer.java:1908) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:518) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:429) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:345) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1102) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
[20:44:21 INFO]: Preparing start region for dimension minecraft:overworld
[20:44:21 INFO]: Time elapsed: 197 ms

Using v. 2.3.0 of pack and 6.4.1 of Terra
![image](https://github.com/justaureus/ReimagEND/assets/129546496/11616de6-3317-4f36-890c-ff1a1948f2bb)
![image](https://github.com/justaureus/ReimagEND/assets/129546496/c1f313b1-fc89-407a-89a4-fc8677a91f37)

**Comment by Skrayti** [comment]
working on 2.2.7 rn, but is it possible to update to 2.3.0 to get content from update?

**Comment by DeathShadez** [comment]
If you're using a newer releases on older versions then you'll have to change every block id that been changed in newer versions to their old ids for that version such as "minecraft:short_grass" to "minecraft:grass".

The logs for when ReimagEnd tries to load will state what block id it cannot load in which you'll have to manually change every instance of their block id or use an older release with less content.

**Comment by Skrayti** [comment]
so I have to change ids inside of pack and where I can get list of them? tried to look for them through Minecraft changelogs, but found nothing usefull
